# Generated by Django 2.0.7 on 2018-08-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('password', models.TextField(db_column='Password')),
                ('createdate', models.TextField(db_column='CreateDate')),
                ('updatedate', models.TextField(blank=True, db_column='UpdateDate', null=True)),
                ('status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
