# Generated by Django 2.0.7 on 2018-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=45)),
                ('content', models.CharField(db_column='Content', max_length=45)),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
    ]
