# Generated by Django 2.0.7 on 2018-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='blog_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='blog_creater', max_length=45)),
                ('title', models.CharField(db_column='blog_title', max_length=45)),
                ('content', models.CharField(db_column='blog_content', max_length=4500)),
                ('createdate', models.DateTimeField(db_column='blog_create_date')),
                ('updatedate', models.DateTimeField(blank=True, db_column='blog_update_date', null=True)),
            ],
            options={
                'db_table': 'my_blog',
                'managed': False,
            },
        ),
    ]
